### ISSUE TITLE
网页版有些地方无法显示

### ISSUE THREAD

**Issue by Kisesy** [yidao620c/python3-cookbook#106]
举个例子：

第六章第一节， "**类似下面这样：**" 下面没东西

![theworld_2016-03-31_20-23-04](https://cloud.githubusercontent.com/assets/5843694/14175807/034d916e-f780-11e5-9f77-3565f7a72f68.png)

第六章第四节也这样，可能还有

原因是 这里的高亮是 code-block:: 如果是 code-block:: text 就没问题，不过也许是别的语法，我对rst不熟悉

**Comment by yidao620c** [comment]
感谢指正

**Comment by yidao620c** [comment]
全部修正完成。

**Comment by yidao620c** [comment]
非常感谢，已经修正。


----
Neng Xiong
WHU, Mathematical and Statistical Institute
Mobile (0086)18520022428
Alternative email, yidao620@163.com
