### ISSUE TITLE
2.5 小节的翻译问题

### ISSUE THREAD

**Issue by woailuoli993** [yidao620c/python3-cookbook#139]
英文原文:

> ## Problem
> 
> You want to search for and replace a text pattern in a string.

我觉得应该把中文翻译的
`你想在字符串中搜索和匹配指定的文本模式`  改为 ->  `你想在字符串中搜索指定的文本模式并替换`

**Comment by woailuoli993** [comment]
还有我在通读在线文档的时候遇到了很多觉得不妥的地方，请问您有维护勘误表吗 @yidao620c

**Comment by syrte** [comment]
@woailuoli993 你可以在 github 上修改后提交 pull request，这样作者只要接受你的修改就行了。
