### ISSUE TITLE
7.3的小问题

### ISSUE THREAD

**Issue by stephenson1811** [yidao620c/python3-cookbook#148]
尽管注解的使用方法可能有很多种，但是它们的主要用途还是文档。 因为python并没有类型声明，通常来讲仅仅通过阅读源码很难知道应该传递什么样的参数给这个函数。 这时候使用注解就能给程序员更多的提示，让他们可以争取的使用函数。

应该是“正确”使用函数

**Comment by yidao620c** [comment]
谢谢指正，您可以去项目上提交pull requests


----
Neng Xiong
WHU, Mathematical and Statistical Institute
Mobile (0086)18520022428
Alternative email, yidao620@163.com

2017-01-10 14:58 GMT+08:00 stephenson1811 <notifications@github.com>:

**Comment by stephenson1811** [comment]
不客气: - )
