### ISSUE TITLE
14.9节 错别字

### ISSUE THREAD

**Issue by se4** [yidao620c/python3-cookbook#149]
**解决问题** 类目下第三段

> 在回溯中**科院**看到，两个异常都被捕获。 要想捕获这样的异常，你可以使用一个简单的 except 语句。 不过，你还可以通过查看异常对象的 __cause__ 属性来跟踪异常链。例如

科院 应该为 可以

**Comment by yidao620c** [comment]
谢谢指正，可以去github上面fork项目，提交pull requests


----
Neng Xiong
WHU, Mathematical and Statistical Institute
Mobile (0086)18520022428
Alternative email, yidao620@163.com

2017-01-31 20:38 GMT+08:00 不插电 <notifications@github.com>:
