### ISSUE TITLE
为什么不托管到gitbook上

### ISSUE THREAD

**Issue by villager10086** [yidao620c/python3-cookbook#156]
个人建议托管到gitbook上，阅读、下载都很方便。

**Comment by yidao620c** [comment]
gitbook速度实在不敢恭维，以后电子书基本都是readthedoc托管。

**Comment by villager10086** [comment]
速度慢吗？我这边教育网的速度还是蛮快的 :smile:

**Comment by yidao620c** [comment]
我曾经对比过，最后放弃了gitbook

**Comment by yidao620c** [comment]
另外还有其他人也这么觉得：

现有的写电子书的方式，有以下几个解决方案，优劣势也很明显。
http://scottming.com/2016/03/27/readthedocs/

自有博客，跟散文堆在一起，不便索引。
GitHub Wiki，适合做知识整理，但排版一般，不方便本地查看。
GitBook，丑，慢。
经过一些比较和调查，最终锁定 Sphinx + GitHub + ReadtheDocs 作为文档写作工具。用 Sphinx 生成文档，GitHub 托管文档，再导入到 ReadtheDocs。

**Comment by yidao620c** [comment]
另外还有其他人也这么觉得：
http://scottming.com/2016/03/27/readthedocs/

现有的写电子书的方式，有以下几个解决方案，优劣势也很明显。

* 自有博客，跟散文堆在一起，不便索引。
* GitHub Wiki，适合做知识整理，但排版一般，不方便本地查看。
* GitBook，丑，慢。

经过一些比较和调查，最终锁定 Sphinx + GitHub + ReadtheDocs 作为文档写作工具。用 Sphinx 生成文档，GitHub 托管文档，再导入到 ReadtheDocs。

**Comment by villager10086** [comment]
原来如此:smile:
