### ISSUE TITLE
Travis CI must be turned on for the tests to run

### ISSUE THREAD

**Issue by cclauss** [yidao620c/python3-cookbook#211]
https://travis-ci.org/yidao620c

**Comment by yidao620c** [comment]
这个是啥

**Comment by cclauss** [comment]
These are the tests that run every time there is a pull request.  Many major Python projects (including Python itself) use Travis Continuous Integration (CI) to make sure that all contributions are automatically tested before they can be merged.  This service is free to open source projects like this one.

* https://github.com/python/cpython/blob/master/.travis.yml
* https://github.com/pallets/flask/blob/master/.travis.yml
* https://github.com/numpy/numpy/blob/master/.travis.yml
