### ISSUE TITLE
中文标点和中英文空格问题

### ISSUE THREAD

**Issue by zwpaper** [yidao620c/python3-cookbook#22]
我看了一下，文中有很多地方还用了英文标点，而且中英文之间没有空格。
在我看来，肯定是应该用中文标点的，所以我看了一下，并把第一章的标点改过来了，后面我再看看修改一下后面的部分。
还有就是中英文之间是应该有一个空格的，不知道大家怎么看？

**Comment by HB6H057** [comment]
感觉还是不用比较好吧。
```
通过使用operator模块的itemgetter函数，可以非常容易的排序这样的数据结构。
```
```
通过使用 operator 模块的 itemgetter 函数，可以非常容易的排序这样的数据结构。
```

**Comment by ilumer** [comment]
在1.2节的讨论的第一个例子里列表与元祖的最后多一个,号
records = [
    ('foo', 1, 2),
    ('bar', 'hello'),
    ('foo', 3, 4),
]

**Comment by yidao620c** [comment]
我也觉得没必要
