### ISSUE TITLE
1.2节的小问题。

### ISSUE THREAD

**Issue by ilumer** [yidao620c/python3-cookbook#32]
在1.2节的讨论的第一个例子里列表与元祖的最后多一个,号
records = [
('foo', 1, 2),
('bar', 'hello'),
('foo', 3, 4),
]

**Comment by yidao620c** [comment]
python里面这个是允许的，^_^

**Comment by ilumer** [comment]
咦，我的pycharm社区版报错不予通过？

**Comment by ilumer** [comment]
刚刚又测试了一下，显示是我的错，抱歉
