### ISSUE TITLE
关于翻译此书的版权问题及若干建议

### ISSUE THREAD

**Issue by sc-syf** [yidao620c/python3-cookbook#331]
想问下这里的翻译是否有取得出版社和作者的同意。

另外，
我觉得出于对作者的尊重，建议在readme的最前面，介绍一下作者(David Beazley大佬)和他的[博客](https://www.dabeaz.com/)之类。

**Comment by yidao620c** [comment]
感谢提醒。作者介绍已经加上了

这里的翻译并未取得作者同意。只是个人兴趣，未使用它做任何的盈利。

----
Neng Xiong
WHU, Mathematical and Statistical Institute
Mobile (0086)18520022428
Alternative email, yidao620@163.com
