### ISSUE TITLE
存在版权问题

### ISSUE THREAD

**Issue by vincent19376** [yidao620c/python3-cookbook#83]
你把别人的书上传上来，又进行翻译，甚至希望收到捐款，这样不合适吧

**Comment by yidao620c** [comment]
请你去看看项目主页，这个项目是我从2014年8月份开始从第一章翻译，历时一年半时间完成，每一个单词都是我自己翻译的 。你先把东西看清楚再说好不好？

**Comment by vincent19376** [comment]
你有翻译授权么？你有被授权翻译之后再传播么？
你付出多大努力不重要，你做的是错的事情。

**Comment by yidao620c** [comment]
刚刚是我误会了，不好意思。非常感谢你的建议。

**Comment by ShujiaHuang** [comment]
我支持你@yidao620c。

**Comment by Gooooodman** [comment]
我支持你@yidao620c

**Comment by godsoul** [comment]
我支持你@yidao620c

**Comment by ZoomQuiet** [comment]
我支持你@yidao620c



-- 
Life's Pathetic, Let's Pythonic! 人生苦短, Python是岸!
俺: http://zoomquiet.io
授: http://creativecommons.org/licenses/by-sa/2.5/cn/
怒: 冗余不做,日子甭过!备份不做,十恶不赦!
KM keep growing environment culture which promoting organization be learnning!

**Comment by chai2010** [comment]
我是来顶译者的：又没有商业目的，去他妈的版权！

PS：我有类似经历，但是被[MDCA](https://github.com/github/dmca/blob/master/2016-02-03-TheGoProgrammingLanguage.md)了。

**Comment by hoperuin** [comment]
我支持你@yidao620c @chai2010 去他妈的版权

**Comment by zuoRambo** [comment]
我是来感谢 @chai2010 的

**Comment by Akagi201** [comment]
去TMD DMCA

**Comment by lbc001** [comment]
辛苦了@yidao620c

**Comment by backspace5544** [comment]
没有意图明显的商业目的，学术交流的翻译又何不可？眼红别人的成就自己就要去努力！！！@支持先
这里是github！！！

**Comment by bright-pan** [comment]
首先，翻译的人没有拿书去盈利，只是接受捐款。
再而翻译都是一个字一个字翻译出来的，属于私有财产，属于自己的笔记，不存在任何法律约束。

**Comment by sniweef** [comment]
无论如何，大力支持作者

**Comment by DYFeng** [comment]
看了下，这本貌似已经有中文翻译卖了，心疼翻译的人。

**Comment by ShujiaHuang** [comment]
好像中译版比这个慢出来的吧~

**Comment by david-wxj** [comment]
很赞呢。

**Comment by overXsky** [comment]
我支持你@yidao620c

**Comment by thisforeda** [comment]
支持译者！

**Comment by bluesway** [comment]
你们这群人到底知不知道什么叫做版权

**Comment by ly0** [comment]
俺们大山里穷，买不起书，英文没人教，话说啥是版权啊？

**Comment by arthas1123** [comment]
這種事還是低調點吧

**Comment by bright-pan** [comment]
再说一次这是一个笔记，不是书，第一他是写给自己看的，第二没有主动传播，第三没有用来盈利，谢谢

如果你们觉得愧疚，那就先买一本书，然后看这个就好了。

**Comment by bluesway** [comment]
连书目和谢辞都有了，排版还一个样，有脸说这只是笔记？大天朝网民把美帝的电视剧拿来翻译了中文字幕之后放到论坛上，说是给自己看的，算不算笔记？是不是也没有营利？一群傻逼

这不是阅读者觉不觉得愧疚的问题，是会不会伤害到作者权利的问题，这种文化素质就别出来丢人了

**Comment by ly0** [comment]
@bluesway 请注意在公共场合的措辞和有民族歧视倾向的言论

**Comment by arthas1123** [comment]
說不過人家就說他言論有問題，吃河蟹吃習慣了嗎？

**Comment by lbc001** [comment]
译者看看能不能向原作者拿个授权吧，

**Comment by yidao620c** [comment]
谢谢大家的建议，已经向原作者发了邮件。

**Comment by bluesway** [comment]
民族会不会被歧视也是要看每个人是不是都能遵守该有的规范，像作者一样以行动证明吧

**Comment by bright-pan** [comment]
每个人心中都有一个哈姆雷特，作者赶紧关闭这个issure吧，受不了一天到晚为这种事情浪费时间。@yidao620c

**Comment by chai2010** [comment]
自己买的正版英文书，有权利自己私下翻译！没有的只是传播的权利，这个权利由原英文出版社申诉，和中国出版社没半毛钱关系，无关网友更没权力指责翻译者！

**Comment by ly0** [comment]
@bluesway 请修改在公众领域会引起他人不适的不友好的言论

**Comment by chai2010** [comment]
@bluesway 国家不够强大再怎么当顺民也是被歧视，就像小rb，版权执行再好还是要被美帝强奸！

**Comment by bluesway** [comment]
@chai2010 放上 Github 公开这样还不算是传播我也是醉了。。。

@ly0 我为自己的言行负责，如果你认为我说的不是事实，可以指出来纠正；你觉得看不惯我这么说话，可以检举我；我的言论就是针对不把版权当一回事还大声嚷嚷的傻逼，所以不会修改。
